name: CI/CD Pipeline

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  # to run tests on PRs
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.19'

      - name: Install dependencies
        run: |
          go mod tidy
          go mod vendor

      - name: Run tests
        run: |
          go test ./...

  #  to build Docker image
  build:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: |
          docker build -t blockhouse-abisheklwagun-trade-api .

      - name: Push Docker image to Docker Hub
        run: |
          docker push blockhouse-abisheklwagun-trade-api:latest

  # to deploy to AWS EC2 instance
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}

      - name: Deploy to EC2
        run: |
          ssh -o StrictHostKeyChecking=no ec2-user@34.215.15.168 'docker pull blockhouse-abisheklwagun-trade-api:latest && docker run -d -p 8080:8080 blockhouse-abisheklwagun-trade-api:latest'

